name: "Hall and Facility Rental Management System"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.4"
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: hfrms_ase
          DB_USER: root
          DB_PASSWORD: root

      - name: Install MySQL
        run: sudo apt-get install mysql-server

      - name: Start MySQL service
        run: sudo service mysql start

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

      - name: Import Database
        run: mysql $DB_DATABASE < database/hfrms_ase.sql
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Run Migrations
        run: php artisan migrate --seed
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        # env:
        #   DB_CONNECTION: mysql
        #   DB_HOST: 127.0.0.1
        #   DB_PORT: 3306
        #   DB_DATABASE: hfrms_ase
        #   DB_USERNAME: root
        #   DB_PASSWORD: MySql@1234
        run: php artisan test
